### ISSUE TITLE
可以提供DEMO嘛？

### ISSUE THREAD

**Issue by twocucao** [AnnaSearl/anna-remax-ui#1]

**Comment by AnnaSearl** [comment]
Demo正在加紧赶工中，过两天会提供的，现在已经已经上线了文档，虽然比较简陋🧎‍♂️，还请先将就一下，后面会逐步完善的

**Comment by AnnaSearl** [comment]
已经更新部分组件的示例了，详情请查看此处[Examples for Anna Remax UI](https://github.com/AnnaSearl/examples-anna-remax-ui)
