### ISSUE TITLE
似乎组件没有按需加载

### ISSUE THREAD

**Issue by PlutoCA** [AnnaSearl/anna-remax-ui#11]
我引用一个button ，文件就已经500kb+了，看打包出来的文件，把其它没有引用的组件也打包进来了

**Comment by AnnaSearl** [comment]
不引入anna-remax-ui看看打包出来的大小是多少

**Comment by AnnaSearl** [comment]
是npm run dev 还是npm run build 打包出来的文件呢

**Comment by PlutoCA** [comment]
dev的会这样，build不会

**Comment by AnnaSearl** [comment]
因为默认情况下webpack只有在production下才会开启tree shaking

**Comment by PlutoCA** [comment]
OK 了解
