### ISSUE TITLE
钉钉交流群二维码似乎无法扫描

### ISSUE THREAD

**Issue by zuigzm** [AnnaSearl/anna-remax-ui#13]

**Comment by AnnaSearl** [comment]
我试了是可以的啊

**Comment by zuigzm** [comment]
![image](https://user-images.githubusercontent.com/16127180/84103915-ed117b80-aa46-11ea-868f-bddb7e342ed4.png)
只显示了一半

**Comment by wlfcss** [comment]
@zuigzm 尝试清除浏览器缓存，强制刷新一下web页

**Comment by zuigzm** [comment]
虽然，在我的电脑上还是没有解决，但已经加群了。看样子要使用重启大法了
