### ISSUE TITLE
button的实现方式

### ISSUE THREAD

**Issue by wlfcss** [AnnaSearl/anna-remax-ui#2]
anna-remax-ui 之中，Button的实现方式并没有依赖 remax/one 的button组件，这是作为何种考虑呢？

**Comment by AnnaSearl** [comment]
其实是应该依赖的，后面我会改为button的，谢谢提醒哦

**Comment by wlfcss** [comment]
不客气，谢谢你的回答，如果能稍微整理一下您的ui的构建思路和目标，我可以参与贡献代码
