### ISSUE TITLE
run build之后，项目里每个wxss都会有一段重复的样式

### ISSUE THREAD

**Issue by theAir** [AnnaSearl/anna-remax-ui#26]
只在app.js 引入 import "anna-remax-ui/esm/popup/style/css";
然后打包后查看每个页面的wxss都会有重复样式。
ui版本是1.8.1。
![WX20200723-115352](https://user-images.githubusercontent.com/17644203/88251173-8d142300-ccdc-11ea-86dc-27cf6fbb7c3b.png)

**Comment by Darmody** [comment]
@theAir 是不是在每个页面都 import 了 app 文件？

**Comment by theAir** [comment]
@Darmody 因为app.js 有一个 createContext，所以大多页面都有import 这个 Context。
但是像截图中间的这个detail页面，并没有import app.js 里的东西

**Comment by Darmody** [comment]
https://github.com/remaxjs/remax/pull/1214
