### ISSUE TITLE
css 微信小程序无法编译通过

### ISSUE THREAD

**Issue by wlfcss** [AnnaSearl/anna-remax-ui#32]
![image](https://user-images.githubusercontent.com/12138285/89486723-47745180-d7d6-11ea-8411-0f602f6b7a8e.png)
![image](https://user-images.githubusercontent.com/12138285/89486949-c9fd1100-d7d6-11ea-970d-c29cc632710e.png)

**Comment by AnnaSearl** [comment]
收到！

**Comment by war408705279** [comment]
求解，遇到了相同的问题~

**Comment by wlfcss** [comment]
> 求解，遇到了相同的问题~

是card组件的css编译无法通过，你按需引用就好了，或者自己把anna组件打包的 css改一下，原因是微信不支持下面这种写法：
``` css
xxxx{
 > * {
...
}
}
```

**Comment by war408705279** [comment]
> > 求解，遇到了相同的问题~
> 
> 是card组件的css编译无法通过，你按需引用就好了，或者自己把anna组件打包的 css改一下，原因是微信不支持下面这种写法：
> 
> ```css
> xxxx{
>  > * {
> ...
> }
> }
> ```

感谢大佬回复  
按需引用可以解决问题，例如在 `pages/wechat/index.tsx` 头部引入 `popup` 组件的样式
```js
import 'anna-remax-ui/esm/popup/style/css'
```
但还是希望可以在下一个 `release` 中根本性解决这个问题 :wink:

**Comment by wlfcss** [comment]
https://github.com/AnnaSearl/anna-remax-ui/commit/aff57266b065c70c034447d1bde094b6e2865bb4
