### ISSUE TITLE
SwipeAction属性open没有作用

### ISSUE THREAD

**Issue by atongmu** [AnnaSearl/anna-remax-ui#35]
SwipeAction属性open无法控制显示隐藏，typescript下报属性错误。

**Comment by AnnaSearl** [comment]
具体场景是怎样呢，能提供demo或代码片段

**Comment by atongmu** [comment]
import React, { useEffect, useState } from 'react';
import { View, Text } from 'remax/wechat';
import { Card, Cell, Icon, SwipeAction } from 'anna-remax-ui';

export default () => {
  const [isLoading, setLoading] = useState(true)
  const [buttons] = useState([{ text: '删除', type: 'warn' }])
  const [list,setItems] = useState([
    { id: 1, name: '11', show: false },
    { id: 2, name: '22', show: false },
  ])

  useEffect(() => {
    const setFun = setTimeout(() => {
      setLoading(false)
    }, 1500)
    return () => {
      setFun
    }
  }, [])
  const handleOpen = (e:any) => {
    console.log(e)
  };
  const handleClose = (e:any) => {
    console.log(e)
  };
  const handleDelete = (e:any) => {
    const newList: any[] = Object.assign([], list)
    for (let i = newList.length - 1; i >= 0; i--) {
      const item = newList[i]
      if (item.id === e.id) {
        item.show = false
        break
      }
    }
    setItems(items => newList)
  };
  return (
    <View>
      <Card>
        {list.map((item: any) => (
          <View key={item.id} className="solid-bottom">
            <SwipeAction open={item.show}
              onOpened={()=>handleOpen(item)}
              onClosed={()=>handleClose(item)}
              options={[
                {
                  name: 'Delete',
                  style: {
                    backgroundColor: '#ff0000',
                  },
                  onTap: (item:any) => handleDelete(item),
                },
              ]}
            >
              <Cell label="Cell" border={false}>
                content
          </Cell>
            </SwipeAction>
          </View>
        ))}
      </Card>
    </View>
  );
};

**Comment by AnnaSearl** [comment]
您好，您的代码有误，我这边帮您修改好了，请按照一下代码运行
`import React, { useState } from 'react';
import { View } from 'remax/wechat';
import { SwipeAction } from 'anna-remax-ui';

export default () => {
  const [list, setItems] = useState([
    { id: 1, name: '11', show: false },
    { id: 2, name: '22', show: false },
  ]);

  const handleOpen = (e: any) => {
    console.log(e);
    setItems(s =>
      s.map(i => {
        return { ...i, show: e.id === i.id ? true : false };
      }),
    );
  };

  const handleClose = (e: any) => {
    console.log(e);
  };

  const handleDelete = (e: any) => {
    const newList: any[] = Object.assign([], list);
    for (let i = newList.length - 1; i >= 0; i--) {
      const item = newList[i];
      if (item.id === e.id) {
        item.show = false;
        break;
      }
    }
    console.log('newList', newList);

    setItems(items => newList);
  };

  console.log('list', list);

  return (
    <View>
      {list.map((item: any) => (
        <SwipeAction
          open={item.show}
          onOpened={() => handleOpen(item)}
          onClosed={() => handleClose(item)}
          options={[
            {
              name: 'Delete',
              style: {
                backgroundColor: '#ff0000',
              },
              onTap: () => handleDelete(item),
            },
          ]}
        >
          jjjj
        </SwipeAction>
      ))}
    </View>
  );
};
`

**Comment by AnnaSearl** [comment]
主要是这行代码有误
`onTap: (item: any) => handleDelete(item)`

**Comment by AnnaSearl** [comment]
ts 报属性错误这个问题确实是有的，我们后续会修复掉的，谢谢指正！
