### ISSUE TITLE
请问下怎么查看支持哪些icon?

### ISSUE THREAD

**Issue by ttwm** [AnnaSearl/anna-remax-ui#9]
icon的type是string类型，请问下有哪些图标可以使用？

**Comment by AnnaSearl** [comment]
[点点点点击此处](https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.d9df05512&cid=33)

**Comment by slobber** [comment]
如何添加自己的icon呢？已经有了自己的collection的话，比如 http://at.alicdn.com/t/font_1373348_kk9y3jk2omq.js

**Comment by AnnaSearl** [comment]
> 如何添加自己的icon呢？已经有了自己的collection的话，比如 http://at.alicdn.com/t/font_1373348_kk9y3jk2omq.js

可以使用自己的icon,但要保证名称不能和anna的重名
